### PR TITLE
Update French (Canada) translation

### PR DESCRIPTION
**Pull request by huguesbrunelle**

### CODE REVIEW

**Comment by huguesbrunelle** [comment]
Hi @softwarerero 
Here is an update to French (Canada) translation.
Regards,

**Comment by huguesbrunelle** [comment]
Hi @softwarerero 
Is it possible for you to review and/or merge this soon? We need some of these translations in our development app for translator review. Thanks 👍

**Comment by softwarerero** [comment]
Sorry that this took so long. I merged it. Is this enough or do you need a release too. I'm traveling right now, so I'm probably not reacting immediately.

**Comment by huguesbrunelle** [comment]
Hi @softwarerero wow thanks for the merge.
It's ok if you do not Release it right away but if that could be in the next 2 weeks that would be awesome! 👍

**Comment by softwarerero** [comment]
2.3.1 is released

**Pull request merged**
