### PR TITLE
Update de.coffee

### PR DESCRIPTION
**Pull request by fknipp**
Moving translations for verification of email addresses to the root, as they aren't translated from errors.accounts within the useraccounts package.

### CODE REVIEW

**Comment by softwarerero** [comment]
I'm not sure about this:
1. Apart from useraccounts this could break a lot of programs depending on it (backward compatibility)?
2. To be consistent we should change this in all languages.

**Comment by fknipp** [comment]
I found a translation for **Verification email lost?** only in **it.coffee**, there's no translation in any other language. And in the Italian file it is on the same position as I suggested in this PR.

I also tried to find the string in the standard accounts package of Meteor, but I didn't find it, so it is very probable, that it is used only in the useraccounts:core package.

**Comment by softwarerero** [comment]
Well you changed also other keys. Some of you keys are also in the Polish translation and others:

```
t9n 509 $ grep "A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder." *
ca.coffee:      "A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder.": "Un nou correu ha estat enviat a la teva bústia. Si no reps el correu assegura't de comprovar la bústia de correu no desitjat."
de.coffee:      "A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder." : "Eine neue Email wurde verschickt. Sollte sich die Email nicht im Posteingang befinden, empfiehlt es sich, den Spamordner zu überprüfen."
en.coffee:      "A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder.": "A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder."
it.coffee:  "A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder.": "Ti è stata inviata una nuova email. Se non trovi l' email nella tua posta in arrivo controllate che non sia stata spostata nella cartella SPAM."
ja.coffee:      "A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder.": "新しいメールを送信しました。もしメールが届いていなければ、迷惑メールに分類されていないか確認してください。"
```

**Comment by fknipp** [comment]
This string is also used in the **useraccounts:core** package, not in standard Meteor accounts package. If you feel more comfortable with it, I can prepare a pull request with duplicate entries on root level as well as on **error.accounts**. 

I did also a Google search on this string:

https://encrypted.google.com/#hl=de&q=%22A%20new%20email%20has%20been%20sent%20to%20you.%20If%20the%20email%20doesn%27t%20show%20up%20in%20your%20inbox%2C%20be%20sure%20to%20check%20your%20spam%20folder.%22

Result: It's only used in the **useraccounts:core** package.

At least, the strings are needed on the root level to make them working with the actual version of useraccounts. Otherwise, I wouldn't have prepared this PR :)

**Comment by softwarerero** [comment]
I trust in your research, let's risk this.

**Pull request merged**
